### ISSUE TITLE
hanging shutdown

### ISSUE THREAD

**Issue by azhurbilo** [zerok/celery-prometheus-exporter#48]
when I run docker-compose down it's waiting for timeout to kill containers with 9 signals

```
celery_exporter:
    image: zerok/celery-prometheus-exporter:latest-celery4
    command: --broker=amqp://{{ mq.user }}:{{ mq.password }}@{{ mq.host }}:{{ mq.port }}/{{ mq.vhost }}
    network_mode: bridge
    mem_limit: {{ (ansible_memory_mb.real.total * 0.1) | round | int }}m
    restart: unless-stopped
    cpus: 0.10
    ports:
      - "9904:8888"
```
> ConnectionResetError: [Errno 104] Connection reset by peer
celery_exporter_1                                              | [2019-04-04 15:28:29,876] kombu.mixins:INFO: Connected to amqp://org:**@mq:5672//org

Can I somehow close container faster and gracefully? (now use workaround - stop_signal: SIGKILL)
